### ISSUE TITLE
Class EnvTypeCheck does not exist

### ISSUE THREAD

**Issue by medv** [silverstripe/silverstripe-environmentcheck#64]
Perhaps I'm doing something wrong. Other checks are working fine using latest version (2.1.2), but when trying to implement the EnvTypeCheck, the class cannot be found.

```
Uncaught SilverStripe\Core\Injector\InjectorNotFoundException: ReflectionException: Class EnvTypeCheck does not exist in /var/www/html/vendor/silverstripe/framework/src/Core/Injector/InjectionCreator.php:17

...

SilverStripe\Core\Injector\InjectionCreator->create(EnvTypeCheck, Array)
Injector.php:594
SilverStripe\Core\Injector\Injector->instantiate(Array, EnvTypeCheck, prototype)
Injector.php:1002
SilverStripe\Core\Injector\Injector->getNamedService(EnvTypeCheck, , Array)
Injector.php:955
SilverStripe\Core\Injector\Injector->get(EnvTypeCheck, , Array)
Injector.php:1125
SilverStripe\Core\Injector\Injector->createWithArgs(EnvTypeCheck, Array)
Injector.php:1113
SilverStripe\Core\Injector\Injector->create(EnvTypeCheck)
EnvironmentCheckSuite.php:137
SilverStripe\EnvironmentCheck\EnvironmentCheckSuite->checkInstances()
EnvironmentCheckSuite.php:110
SilverStripe\EnvironmentCheck\EnvironmentCheckSuite->run()
EnvironmentChecker.php:169
```

environmentcheck.yml
```
---
Name: my-environmentcheck
---
SilverStripe\EnvironmentCheck\EnvironmentCheckSuite:
  registered_checks:
    db:
      definition: 'DatabaseCheck("SiteTree")'
      title: 'Database'
    url:
      definition: 'URLCheck("/")'
      title: 'Site'
    external:
      definition: 'ExternalURLCheck("https://www.google.com")'
      title: 'Internet'
    env:
      definition: 'EnvTypeCheck' # tried with EnvTypeCheck() and EnvTypeCheck("live")
      title: 'Environment'
  registered_suites:
    health:
      - db
      - url
      - external
      - env
    check:
      - db
      - url
      - external
      - env
```

**Comment by Cheddam** [comment]
Hey @medv, thanks for raising this! The issue is that this particular check was introduced without an alias to allow usage without the full namespace. I've raised a PR to address this, but in the meantime you can use it by specifying the namespace:

```yml
---
Name: my-environmentcheck
---
SilverStripe\EnvironmentCheck\EnvironmentCheckSuite:
  registered_checks:
    env:
      definition: 'SilverStripe\EnvironmentCheck\Checks\EnvTypeCheck'
      title: 'Environment'
```
